### ISSUE TITLE
Manual Installation on Ubuntu 22.04.1 LTS: "a different version of babel-jest"

### ISSUE THREAD

**Issue by BTCBellyButton** [joinmarket-webui/jamdocs#13] opened 2022-09-16 21:49 UTC
So I was trying to manually install Jam on my Ubuntu 22.04.1 and to connect it to an existing JM instance running on another machine on my LAN.

After doing:
`ssh 192.168.1.8 -v -o GatewayPorts=true -N -L 28183:127.0.0.1:28183 -L 28283:127.0.0.1:28283 -L 62601:127.0.0.1:62601`

I try to run it:

> npm start
> 
> > jam@0.0.10 start
> > react-scripts start
> 
> 
> There might be a problem with the project dependency tree.
> It is likely not a bug in Create React App, but something you need to fix locally.
> 
> The react-scripts package provided by Create React App requires a dependency:
> 
>   "babel-jest": "23.6.0"
> 
> Don't try to install it manually: your package manager does it automatically.
> However, a different version of babel-jest was detected higher up in the tree:
> 
>   /home/xx/jam/node_modules/babel-jest (version: 27.5.1) 
> 
> Manually installing incompatible versions is known to cause hard-to-debug issues.
> 
> If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
> That will permanently disable this message but you might encounter other issues.
> 
> To fix the dependency tree, try following the steps below in the exact order:
> 
>   1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
>   2. Delete node_modules in your project folder.
>   3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
>   4. Run **npm** install or yarn, depending on the package manager you use.
> 
> In most cases, this should be enough to fix the problem.

I tried 1,2,4 but there's no "babel-jest" in the package.json file:

> "devDependencies": {
>     "@emotion/react": "^11.9.3",
>     "@popperjs/core": "^2.11.5",
>     "@table-library/react-table-library": "^4.0.10",
>     "@testing-library/jest-dom": "^5.16.4",
>     "@testing-library/react": "^12.1.4",
>     "@testing-library/user-event": "^13.5.0",
>     "@types/jest": "^27.5.1",
>     "@types/node": "^17.0.35",
>     "@types/react": "^17.0.43",
>     "@types/react-dom": "^17.0.14",
>     "bootstrap": "^5.2.0",
>     "buffer": "^6.0.3",
>     "classnames": "^2.3.1",
>     "conventional-changelog": "^3.1.25",
>     "formik": "^2.2.9",
>     "http-proxy-middleware": "^2.0.6",
>     "husky": "^8.0.1",
>     "i18next": "^21.8.4",
>     "i18next-browser-languagedetector": "^6.1.4",
>     "jest-watch-typeahead": "^0.6.5",
>     "jest-websocket-mock": "^2.3.0",
>     "lint-staged": "^12.4.2",
>     "prettier": "^2.6.2",
>     "qrcode": "^1.5.0",
>     "react": "^17.0.2",
>     "react-bootstrap": "^2.5.0-beta.1",
>     "react-dom": "^17.0.2",
>     "react-i18next": "^11.16.9",
>     "react-router-bootstrap": "^0.26.2",
>     "react-router-dom": "^6.3.0",
>     "react-scripts": "^2.1.3",
>     "typescript": "^4.7.2",
>     "web-vitals": "^2.1.4"
>   },
>   "dependencies": {
>     "serve": "13.0.2"
>   },
>

**Comment by theborakompanioni** [comment] 2022-09-17 13:55
Hey! Thanks for the report!

What node and npm version are you running?
Currently cannot reproduce with node `v16.17.0` and npm `v8.15.0`.

Would running the ui-only docker image be a viable workaround for you?
edit: Please see the [updated instructions](https://github.com/joinmarket-webui/jamdocs/pull/14) and make sure you are running JM `v0.9.8` as backend

**Comment by BTCBellyButton** [comment] 2022-09-18 02:37
```
node -v
v16.17.0

npm -v
8.15.0
```

I can try docker but I am not sure if I can install Jam only. I already have a JoinMarket v0.9.7 instance running and I'd like to connect to that one, which is running on a separate dedicated machine.

Will this do that?

```
. jmvenv/bin/activate
python3 scripts/jmwalletd.py

. jmvenv/bin/activate
python3 scripts/obwatch/ob-watcher.py --host=127.0.0.1

ssh 192.168.1.8 -v -o GatewayPorts=true -N -L 28183:127.0.0.1:28183 -L 28283:127.0.0.1:28283 -L 62601:127.0.0.1:62601

# Option 1: run Jam via docker

docker run --rm  -it \
        --add-host=host.docker.internal:host-gateway \
        --env JMWEBUI_JMWALLETD_HOST="host.docker.internal" \
        --env JMWEBUI_JMWALLETD_API_PORT="28183" \
        --env JMWEBUI_JMWALLETD_WEBSOCKET_PORT="28283" \
        --publish "8080:80" \
        ghcr.io/joinmarket-webui/jam-ui-only:v0.1.0-clientserver-v0.9.8
```

**Comment by theborakompanioni** [comment] 2022-09-19 07:59
> I can try docker but I am not sure if I can install Jam only. I already have a JoinMarket v0.9.7 instance running and I'd like to connect to that one, which is running on a separate dedicated machine.

For Jam v0.1.0 you should update to v0.9.8 if you can do so easily... It has one important bug fix for scheduled sweeps, which enables the Stall Monitor and prevents the process from "getting stuck".

> 
> Will this do that?
> 
> ```
> . jmvenv/bin/activate
> python3 scripts/jmwalletd.py
> 
> . jmvenv/bin/activate
> python3 scripts/obwatch/ob-watcher.py --host=127.0.0.1
> 
> ssh 192.168.1.8 -v -o GatewayPorts=true -N -L 28183:127.0.0.1:28183 -L 28283:127.0.0.1:28283 -L 62601:127.0.0.1:62601

Yes!

> # Option 1: run Jam via docker
> 
> docker run --rm  -it \
>         --add-host=host.docker.internal:host-gateway \
>         --env JMWEBUI_JMWALLETD_HOST="host.docker.internal" \
>         --env JMWEBUI_JMWALLETD_API_PORT="28183" \
>         --env JMWEBUI_JMWALLETD_WEBSOCKET_PORT="28283" \
>         --publish "8080:80" \
>         ghcr.io/joinmarket-webui/jam-ui-only:v0.1.0-clientserver-v0.9.8
> ```

See https://github.com/joinmarket-webui/jam-docker#run - the env vars prefix changed from `JMWEBUI_` to `JAM_`, and you'd need to add `JAM_JMOBWATCH_PORT`. Otherwise - looks good! Let me know if it worked for you.

```
docker run --rm  -it \
         --add-host=host.docker.internal:host-gateway \
         --env JAM_JMWALLETD_HOST="host.docker.internal" \
         --env JAM_JMWALLETD_API_PORT="28183" \
         --env JAM_JMWALLETD_WEBSOCKET_PORT="28283" \
         --env JAM_JMOBWATCH_PORT="62601" \
         --publish "8080:80" \
         ghcr.io/joinmarket-webui/jam-ui-only:v0.1.0-clientserver-v0.9.8
```

That so strange.
> ```
> node -v
> v16.17.0
> 
> npm -v
> 8.15.0
> ```

I will maybe transfer the issue to the `jam` repo and try to fix it there. Again, cannot reproduce at the moment. Will report back. Thanks for the report! :orange_heart:

**Comment by BTCBellyButton** [comment] 2022-09-19 15:47
I'll try when I have some time, and let you know.
One thing is worth mentioning, I believe. 
On the machine running JoinMarket I am using JoininBox. So maybe that environment isn't the best starting point for trying Jam and possibly it's the source of weird issues? Even though the machine from where I want to run Jam has none of that stuff.

**Comment by theborakompanioni** [comment] 2022-09-19 15:55
> I'll try when I have some time, and let you know. One thing is worth mentioning, I believe. On the machine running JoinMarket I am using JoininBox. So maybe that environment isn't the best starting point for trying Jam and possibly it's the source of weird issues? Even though the machine from where I want to run Jam has none of that stuff.

I am sorry but I can only make uninformed guesses about this. I have never heard of any incompatibilities from anyone before, but that does not mean that there are none.[ This PR](https://github.com/joinmarket-webui/jam/pull/505) updates the dependencies, which I hope could at least theoretically fix your problem (still, without being able to reproduce it). I'll ping you here when it got merged.

**Comment by BTCBellyButton** [comment] 2022-10-05 20:39
I could finally start it.
One thing should be added to the document section "...connecting to a remote JoinMarket instance".
Something like:

> Once started, go to http://localhost:8080/ in your browser.

It took me some time to figure out that it wasn't running on port 3000 as said few lines above...

BUT I get this error:
![image](https://user-images.githubusercontent.com/68573637/194159277-21f97974-36d8-4ca0-9e7c-bf37abb4f711.png)

What should I check?

**Comment by theborakompanioni** [comment] 2022-10-06 11:01
> It took me some time to figure out that it wasn't running on port 3000 as said few lines above...

Oh, yes. m( 
Thanks - updated accordingly: https://github.com/joinmarket-webui/jamdocs/pull/20

Once merged, the "standalone" example with docker will use port 8080 - the "local/remote" examples will use port 3000.

> 
> BUT I get this error: ![image](https://user-images.githubusercontent.com/68573637/194159277-21f97974-36d8-4ca0-9e7c-bf37abb4f711.png)
> 
> What should I check?

Pardon the question, but if it is running on port 8080, I assume you are using the docker `ui-only` image now (instead of with `npm`), is that correct?
Also I assume, you are still trying to connect to a remote instance, right?

If you are connecting to a remote instance, make sure that the tunnel is working correctly:
```
ssh yourhost.local -v -o GatewayPorts=true -N -L 28183:127.0.0.1:28183 -L 28283:127.0.0.1:28283 -L 62601:127.0.0.1:62601
```
(I am not completely sure whether the tunnel must be created before starting the docker image - should not be necessary, but did not verify. To be safe, start the tunnel before running the container).

Then check that the `jmwalletd` service is reachable from you host, e.g. with:
```
curl -ksX GET https://127.0.0.1:28183/api/v1/session
```

This should response with something like:
```
{"session": false, "maker_running": false, "coinjoin_in_process": false, "schedule": null, "wallet_name": "None", "offer_list": null, "nickname": null}
```

If you don't get this response, make sure that the service is actually running and that the ports match. `28183` is the default port for `jmwalletd`, see https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/v0.9.8/docs/JSON-RPC-API-using-jmwalletd.md#introduction---how-to-start-the-server

e.g. execute the `curl` request on the remote machine.

After a solution is found, I will update the FAQ section https://jamdocs.org/FAQ/#no-connection-to-gateway with the findings. :pray:

**Comment by BTCBellyButton** [comment] 2022-10-06 22:29
> Pardon the question, but if it is running on port 8080, I assume you are using the docker ui-only image now (instead of with npm), is that correct?


Correct

> Also I assume, you are still trying to connect to a remote instance, right?

Yes

Start jmwalletd.py on remote JM machine:

![image](https://user-images.githubusercontent.com/68573637/194426948-bfaeda6d-12a6-425b-8b94-ccbcce24303f.png)

Start tunnel on local JAM machine, Tested on remote JM machine:

![image](https://user-images.githubusercontent.com/68573637/194429506-0856a5b5-65da-4815-903e-01ca34bab86a.png)

Run docker on local JAM machine:
![image](https://user-images.githubusercontent.com/68573637/194428947-36abbff8-5a96-4a11-9185-39192bd82693.png)

Run JAM in browser on local JAM machine, no connection:
![image](https://user-images.githubusercontent.com/68573637/194429781-7b2fa344-17ea-4e3f-88ec-add38401fb27.png)

**Comment by theborakompanioni** [comment] 2023-09-23 08:37
@BTCBellyButton Have you been able to make it work?

**Comment by theborakompanioni** [comment] 2023-09-23 10:18
Ran into the same situation today with a local tunnel and `--add-host host.docker.internal:host-gateway`.
Solution was to either run on the host network with `--network host` or exposing the tunnel ports on `0.0.0.0` instead of `127.0.0.1`.

Instead of
```shell
ssh yourhost.local -v -o GatewayPorts=true -N -L 28183:127.0.0.1:28183 -L 28283:127.0.0.1:28283 -L 62601:127.0.0.1:62601
```
use
```shell
ssh yourhost.local -v -o GatewayPorts=true -N -L 0.0.0.0:28183:127.0.0.1:28183 -L 0.0.0.0:28283:127.0.0.1:28283 -L 0.0.0.0:62601:127.0.0.1:62601
```

This is not optimal (as it exposes the ports on your local network) but can be a temporary workaround.

Closing this issue now, please reopen on demand.

**Closed as completed by theborakompanioni** 2023-09-23 10:18 UTC
